### ISSUE TITLE
Add support for apple m1 aarch64 architecture

### ISSUE THREAD

**Issue by fkoehler** [scalameta/metals-feature-requests#185]
I am using the Visual Studio Developer Preview to have a native VS Code for new macos big sure running on the M1 chip.

Using the preview release of the openjdk for aarch64 (https://github.com/microsoft/openjdk-aarch64/releases)
I get the following errors when trying to import a simple project (using  metals 0.9.10). The error might be bloop related?! I am not sure:

```
[0m2021.02.02 10:58:58 INFO  Started: Metals version 0.9.10 in workspace '/Users/fab/dev/ista/rdm/common' for client vscode 1.53.0-insider.[0m
[0m2021.02.02 10:58:59 INFO  time: initialize in 0.85s[0m
[0m2021.02.02 10:58:59 WARN  Build server is not auto-connectable.[0m
java.lang.NoSuchFieldException: ucp
	at java.base/java.lang.Class.getDeclaredField(Class.java:2554)
	at scala.meta.internal.mtags.ClasspathLoader$.getURLs(ClasspathLoader.scala:39)
	at scala.meta.internal.metals.PackageIndex$.findJar(PackageIndex.scala:199)
	at scala.meta.internal.metals.PackageIndex$.scalaLibrary(PackageIndex.scala:206)
	at scala.meta.internal.metals.Compilers.ramboCompiler$lzycompute(Compilers.scala:90)
	at scala.meta.internal.metals.Compilers.ramboCompiler(Compilers.scala:89)
	at scala.meta.internal.metals.InteractiveSemanticdbs.$anonfun$compile$5(InteractiveSemanticdbs.scala:171)
	at scala.Option.getOrElse(Option.scala:189)
	at scala.meta.internal.metals.InteractiveSemanticdbs.compile(InteractiveSemanticdbs.scala:171)
	at scala.meta.internal.metals.InteractiveSemanticdbs.$anonfun$textDocument$1(InteractiveSemanticdbs.scala:88)
	at java.base/java.util.HashMap.compute(HashMap.java:1320)
	at java.base/java.util.Collections$SynchronizedMap.compute(Collections.java:2732)
	at scala.meta.internal.metals.InteractiveSemanticdbs.textDocument(InteractiveSemanticdbs.scala:84)
	at scala.meta.internal.metals.AggregateSemanticdbs.loop$1(AggregateSemanticdbs.scala:30)
	at scala.meta.internal.metals.AggregateSemanticdbs.textDocument(AggregateSemanticdbs.scala:36)
	at scala.meta.internal.decorations.SyntheticsDecorationProvider.currentDocument(SyntheticsDecorationProvider.scala:243)
	at scala.meta.internal.decorations.SyntheticsDecorationProvider.publishSynthetics(SyntheticsDecorationProvider.scala:66)
	at scala.meta.internal.metals.MetalsLanguageServer.didOpen(MetalsLanguageServer.scala:895)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
[0m2021.02.02 10:59:01 INFO  no build target: using presentation compiler with only scala-library[0m
[0m2021.02.02 10:59:01 WARN  no build target for: /Users/fab/dev/ista/rdm/common/cache/src/main/scala/com/ista/rdm/common/cache/CacheComponents.scala[0m
[0m2021.02.02 10:59:02 INFO  running '/opt/homebrew/opt/openjdk/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/6v/b36l957d01v41ttc6tq4k_580000gn/T/metals1994838072967944729/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'[0m
Exception in thread "pool-1-thread-6" java.lang.UnsatisfiedLinkError: /Users/fab/Library/Caches/JNA/temp/jna1573164620128123865.tmp: dlopen(/Users/fab/Library/Caches/JNA/temp/jna1573164620128123865.tmp, 1): no suitable image found.  Did find:
	/Users/fab/Library/Caches/JNA/temp/jna1573164620128123865.tmp: no matching architecture in universal wrapper
	/Users/fab/Library/Caches/JNA/temp/jna1573164620128123865.tmp: no matching architecture in universal wrapper
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2383)
	at java.base/java.lang.Runtime.load0(Runtime.java:746)
	at java.base/java.lang.System.load(System.java:1857)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:87)
	at com.zaxxer.nuprocess.internal.LibC.<clinit>(LibC.java:38)
	at com.zaxxer.nuprocess.osx.ProcessKqueue.<clinit>(ProcessKqueue.java:58)
	at com.zaxxer.nuprocess.osx.OsxProcess.<clinit>(OsxProcess.java:42)
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:33)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:259)
	at scala.meta.internal.builds.ShellRunner.run(ShellRunner.scala:79)
	at scala.meta.internal.builds.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:70)
	at scala.meta.internal.builds.BloopInstall.$anonfun$runUnconditionally$1(BloopInstall.scala:44)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall(BloopInstallProvider.scala:21)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall$(BloopInstallProvider.scala:16)
	at scala.meta.internal.builds.SbtBuildTool.bloopInstall(SbtBuildTool.scala:15)
	at scala.meta.internal.builds.BloopInstall.runUnconditionally(BloopInstall.scala:42)
	at scala.meta.internal.builds.BloopInstall.$anonfun$runIfApproved$2(BloopInstall.scala:125)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
[0m2021.02.02 10:59:22 INFO  running '/opt/homebrew/opt/openjdk/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/6v/b36l957d01v41ttc6tq4k_580000gn/T/metals10135121040158258773/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'[0m
Exception in thread "pool-1-thread-4" java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.nuprocess.osx.OsxProcess
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:33)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:259)
	at scala.meta.internal.builds.ShellRunner.run(ShellRunner.scala:79)
	at scala.meta.internal.builds.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:70)
	at scala.meta.internal.builds.BloopInstall.$anonfun$runUnconditionally$1(BloopInstall.scala:44)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall(BloopInstallProvider.scala:21)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall$(BloopInstallProvider.scala:16)
	at scala.meta.internal.builds.SbtBuildTool.bloopInstall(SbtBuildTool.scala:15)
	at scala.meta.internal.builds.BloopInstall.runUnconditionally(BloopInstall.scala:42)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBloopServer(MetalsLanguageServer.scala:1836)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$slowConnectToBuildServer$3(MetalsLanguageServer.scala:1819)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
[0m2021.02.02 10:59:24 INFO  running '/opt/homebrew/opt/openjdk/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/6v/b36l957d01v41ttc6tq4k_580000gn/T/metals9396489880053276991/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'[0m
Exception in thread "pool-1-thread-10" java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.nuprocess.osx.OsxProcess
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:33)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:259)
	at scala.meta.internal.builds.ShellRunner.run(ShellRunner.scala:79)
	at scala.meta.internal.builds.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:70)
	at scala.meta.internal.builds.BloopInstall.$anonfun$runUnconditionally$1(BloopInstall.scala:44)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall(BloopInstallProvider.scala:21)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall$(BloopInstallProvider.scala:16)
	at scala.meta.internal.builds.SbtBuildTool.bloopInstall(SbtBuildTool.scala:15)
	at scala.meta.internal.builds.BloopInstall.runUnconditionally(BloopInstall.scala:42)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBloopServer(MetalsLanguageServer.scala:1836)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$slowConnectToBuildServer$3(MetalsLanguageServer.scala:1819)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
[0m2021.02.02 10:59:24 INFO  running '/opt/homebrew/opt/openjdk/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /var/folders/6v/b36l957d01v41ttc6tq4k_580000gn/T/metals3734433425062217325/sbt-launch.jar -Dbloop.export-jar-classifiers=sources bloopInstall'[0m
Exception in thread "pool-1-thread-11" java.lang.NoClassDefFoundError: Could not initialize class com.zaxxer.nuprocess.osx.OsxProcess
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:33)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:259)
	at scala.meta.internal.builds.ShellRunner.run(ShellRunner.scala:79)
	at scala.meta.internal.builds.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:70)
	at scala.meta.internal.builds.BloopInstall.$anonfun$runUnconditionally$1(BloopInstall.scala:44)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall(BloopInstallProvider.scala:21)
	at scala.meta.internal.builds.BloopInstallProvider.bloopInstall$(BloopInstallProvider.scala:16)
	at scala.meta.internal.builds.SbtBuildTool.bloopInstall(SbtBuildTool.scala:15)
	at scala.meta.internal.builds.BloopInstall.runUnconditionally(BloopInstall.scala:42)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBloopServer(MetalsLanguageServer.scala:1836)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$slowConnectToBuildServer$3(MetalsLanguageServer.scala:1819)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Feb. 02, 2021 11:08:14 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFORMATION: Unsupported notification method: $/setTraceNotification
```

**Comment by kpbochenek** [comment]
The problem here is openjdk for aarch64 is based on JDK16 which is far from being officially supported by metals.

It is only Metals relased, classes that are used by metals in JDK are removed in V16
https://github.com/Col-E/Recaf/issues/312

**Comment by kpbochenek** [comment]
```
        // jdk.internal.loader.ClassLoaders.AppClassLoader.ucp
        val ucpField = classLoader.getClass().getDeclaredField("ucp")
```
:sweat_smile: 
maybe another else case for 16+ could do the trick :)

**Comment by tgodzik** [comment]
This should work correctly now.
