### ISSUE TITLE
Add ability to configure debug session start timeout

### ISSUE THREAD

**Issue by franekfm** [scalameta/metals-feature-requests#323]
### Is your feature request related to a problem? Please describe.

when I try to run debugSession/start for a big application with many deps I am getting following error:
`java.util.concurrent.TimeoutException: Future timed out after [60 seconds]`
from this line in particular:
`  at scala.meta.internal.metals.MetalsEnrichments$XtensionScalaFuture.$anonfun$withTimeout$1(MetalsEnrichments.scala:204)`
I would love to have this timeout configurable. Currently it seems to be hardcoded to 60 seconds :(

My Metals version is `0.11.9`.

The stack trace:
```
[Error - 1:33:41 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: Future timed out after [60 seconds]
  at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
  at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
  at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:661)
  at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
  at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
  at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
  at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
  at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
  at scala.concurrent.ExecutionContext$parasitic$.execute(ExecutionContext.scala:222)
  at scala.concurrent.impl.Promise$Transformation.submitWithValue(Promise.scala:429)
  at scala.concurrent.impl.Promise$DefaultPromise.submitWithValue(Promise.scala:338)
  at scala.concurrent.impl.Promise$DefaultPromise.tryComplete0(Promise.scala:285)
  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:504)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Future timed out after [60 seconds]
  at scala.concurrent.impl.Promise$DefaultPromise.tryAwait0(Promise.scala:248)
  at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:261)
  at scala.concurrent.Await$.$anonfun$result$1(package.scala:201)
  at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:62)
  at scala.concurrent.Await$.result(package.scala:124)
  at scala.meta.internal.metals.MetalsEnrichments$XtensionScalaFuture.$anonfun$withTimeout$1(MetalsEnrichments.scala:204)
  at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
  at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
  ... 3 more
```

### Describe the solution you'd like

`  at scala.meta.internal.metals.MetalsEnrichments$XtensionScalaFuture.$anonfun$withTimeout$1(MetalsEnrichments.scala:204)`
I would love to have this timeout configurable. Currently it seems to be hardcoded to 60 seconds :(

### Describe alternatives you've considered

stop using Metals with VSCode and get back to terrible IntelliJ IDEA :(

### Additional context

a corpo world with many constraints about version of many components or way things are done

### Search terms

vscode metals debug start timeout

**Comment by ckipp01** [comment]
Thanks for the report @franekfm. However,  this might be a red herring. It is timing out, but the server shouldn't take over 60 seconds just to start the debug session.

https://github.com/scalameta/metals/blob/1cbc85ca3c3a04b0129587f719abe11791992bbc/metals/src/main/scala/scala/meta/internal/metals/debug/DebugProvider.scala#L134-L148

As you can see above it should actually ensure everything is compiled first, and then start the session. Are you using the default Bloop here as your build server? Also, does debugging work for you in a minimal project in this same environment?
