### ISSUE TITLE
Support JDK8

### ISSUE THREAD

**Issue by Sigma711** [scalameta/metals-feature-requests#396]
### Is your feature request related to a problem? Please describe.

Metals for VSCode used to support JDK8 before. There are many old projects so it is still essential. Thanks!

### Describe the solution you'd like

Please make the extension support JDK8.

### Describe alternatives you've considered

Maybe you can put some parts of old version into the latest version.

### Search terms

JDK8

**Comment by tgodzik** [comment]
Thanks for reporting! If you need to work with JDK 8, you only need to set `metals.javaHome` to your JDK 8 installation. The version JDK used by Metals is separate to what a project uses.

**Comment by Sigma711** [comment]
> Thanks for reporting! If you need to work with JDK 8, you only need to set `metals.javaHome` to your JDK 8 installation. The version JDK used by Metals is separate to what a project uses.

This is the error info:

```
Metals version: 1.3.5
Using coursier located at /Users/zhuhongrui/.metals/cs
Checking Java in JAVA_HOME, which points to /Users/zhuhongrui/.sdkman/candidates/java/current
	openjdk version "1.8.0_422"
	OpenJDK Runtime Environment (Zulu 8.80.0.17-CA-macos-aarch64) (build 1.8.0_422-b05)
	OpenJDK 64-Bit Server VM (Zulu 8.80.0.17-CA-macos-aarch64) (build 25.422-b05, mixed mode)
Java version doesn't match the required one of 11
Searching for Java on PATH. Found java executable under /Users/zhuhongrui/.sdkman/candidates/java/current/bin/java that resolves to /Users/zhuhongrui/.sdkman/candidates/java/8.0.422-zulu/zulu-8.jdk/Contents/Home/bin/java
	openjdk version "1.8.0_422"
	OpenJDK Runtime Environment (Zulu 8.80.0.17-CA-macos-aarch64)
	(build 1.8.0_422-b05)
	OpenJDK 64-Bit Server VM (Zulu 8.80.0.17-CA-macos-aarch64) (build 25.422-b05, mixed mode)
Java version doesn't match the required one of 11
No installed java with version 11 found. Will fetch one using coursier:
	Downloading https://github.com/coursier/jvm-index/raw/master/index.json
	Downloaded https://github.com/coursier/jvm-index/raw/master/index.json
	Exception in thread "main" java.lang.Exception: Error while getting https://github.com/coursier/jvm-index/raw/master/index.json: download error: Caught java.net.ConnectException (Connection refused) while downloading https://github.com/coursier/jvm-index/raw/master/index.json
	at coursier.jvm.JvmIndex$.$anonfun$load$5(JvmIndex.scala:142)
	at coursier.jvm.JvmIndex$.$anonfun$load$5$adapted(JvmIndex.scala:140)
	at coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
	at coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
		at coursier.util.Task$.wrap(Task.scala:82)
	at coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
		at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
		at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.lang.Thread.run(Thread.java:833)
	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Error: Process exited with code 1
Release notes was not shown: not showing release notes since they've already been seen for your current version
```

And it cannot import Scala for Java.

**Comment by tgodzik** [comment]
For metals to work itself you need JDK at least 11, preferably 17 as Metals and a lot of libraries it depends on already dropped support for JDK 8. We do try to download Java automatically if possible, but it seems that does not work on you machine. Are you behind a proxy and github is not accessible to you?

Unfortunately, there is nothing else to download and install it manually then. Metals will not run on JDK 8 (soon JDK 11), that's expected and a lot of tools and libraries are doing the same. We do provide ways to compile your projects with a specific JDK API, which should be enough for most cases.
