### ISSUE TITLE
Replace usage of NuProcess with Java Process

### ISSUE THREAD

**Issue by matthughes** [scalameta/metals-feature-requests#51]
**Describe the bug**
Metals in VSCode frequently fails to import my project.  The same SBT command used on the command line, fails in Metals 80% of the time with the following error:

```
INFO  running '/usr/local/bin/sbt -sbt-dir /Users/mhughe008/.sbtenv/vise -ivy /Users/mhughe008/.sbtenv/vise/ivy2 -mem 4098 metalsEnable bloopInstall'
Oct 22, 2019 9:37:32 AM com.zaxxer.nuprocess.osx.OsxProcess start
WARNING: Exception thrown from handler
java.lang.RuntimeException: Invocation of posix_spawn() failed, return code: 2, last error: 17
	at com.zaxxer.nuprocess.internal.BasePosixProcess.checkReturnCode(BasePosixProcess.java:639)
	at com.zaxxer.nuprocess.osx.OsxProcess.start(OsxProcess.java:85)
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at scala.meta.internal.metals.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:80)
	at scala.meta.internal.metals.BloopInstall.runUnconditionally(BloopInstall.scala:55)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1194)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1168)
	at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1038)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

INFO  build tool exit: -2147483648
INFO  time: ran 'sbt bloopInstall' in 2ms
```

**To Reproduce**
1. Import project with SBT arguments
2. Import fails

**Expected behavior**
SBT command should succeed and project should be imported.

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.7.6
- Also using Bloop 1.3.4 external server

**Additional context**
This seems to be made worse when I'm switching branches and need to re-import.  It's like Bloop is still holding onto the previous project definition.  However, I'm not sure how much sense this makes as the same SBT command succeeds on the CLI every time.

**Comment by matthughes** [comment]
So even when generating project using "sbt bloopInstall metalsEnable", using external Bloop, not using Metals to import, I still don't have references reliably working:

This is what bloop and metals report after VSCode startup on a compiling project:

metals
```
INFO  time: initialize in 2.65s
INFO  running installed 'bloop bsp --protocol local --socket /var/folders/6j/5kj3c4nj26s5gvv_q74x4_w40000gp/T/bsp1978979851463865632/cpxgo3x0pfzm.socket'
INFO  skipping build import with status 'Requested'
INFO  The server is listening for incoming connections at local:///var/folders/6j/5kj3c4nj26s5gvv_q74x4_w40000gp/T/bsp1978979851463865632/cpxgo3x0pfzm.socket...
INFO  Accepted incoming BSP client connection at local:///var/folders/6j/5kj3c4nj26s5gvv_q74x4_w40000gp/T/bsp1978979851463865632/cpxgo3x0pfzm.socket
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /Users/mhughe008/Library/Caches/org.scalameta.metals/bsp.trace.json
INFO  request received: build/initialize
INFO  time: connected to build server in 0.68s
INFO  BSP initialization handshake complete.
INFO  time: imported build in 0.3s
INFO  time: indexed workspace in 4.03s
WARN  no build target:
```

bloop:
```
[W] Internal error in session

==> log/bloop/bloop.err.log <==
java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
	at com.martiansoftware.nailgun.NGCommunicator.readCommandContext(NGCommunicator.java:140)
	at com.martiansoftware.nailgun.NGSession.run(NGSession.java:197)
```

Metals Doctor tells me to "Import Build" to resolve the issues but 1) that process always dies and 2) why should I need that?  Doesn't that just run the same thing I ran with SBT?

**Comment by olafurpg** [comment]
@matthughes can you please open a new issue in https://github.com/scalameta/metals/ ? We took the liberty to focus this issue here on fixing the stack trace
```
java.lang.RuntimeException: Invocation of posix_spawn() failed, return code: 2, last error: 17
	at com.zaxxer.nuprocess.internal.BasePosixProcess.checkReturnCode(BasePosixProcess.java:639)
```
and the problem you're describing looks unrelated. Please include the Metals version, bloop version, editor, etc. It would be good if you can also elaborate on   "don't have references reliably working"

**Comment by ZiluTian** [comment]
Hello, 
I am facing the same issue. Any solution? 
Stack trace: 
```
INFO  started: Metals version 0.8.0 in workspace '/Users/test/test'
INFO  time: initialize in 0.43s
INFO  running 'SBT_OPTS="-Xss128m" set bloopExportJarClassifiers in Global := Some(Set("sources")) bloopInstall'
Feb 14, 2020 3:21:25 PM com.zaxxer.nuprocess.osx.OsxProcess start
WARNING: Exception thrown from handler
java.lang.RuntimeException: Invocation of posix_spawn() failed, return code: 2, last error: 2
	at com.zaxxer.nuprocess.internal.BasePosixProcess.checkReturnCode(BasePosixProcess.java:639)
	at com.zaxxer.nuprocess.osx.OsxProcess.start(OsxProcess.java:85)
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at scala.meta.internal.metals.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:80)
	at scala.meta.internal.metals.BloopInstall.$anonfun$runUnconditionally$1(BloopInstall.scala:53)
	at scala.meta.internal.builds.BloopPluginBuildTool.bloopInstall(BloopPluginBuildTool.scala:15)
	at scala.meta.internal.metals.BloopInstall.runUnconditionally(BloopInstall.scala:51)
	at scala.meta.internal.metals.BloopInstall.$anonfun$runIfApproved$2(BloopInstall.scala:160)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

INFO  build tool exit: -2147483648
INFO  time: ran 'sbt bloopInstall' in 0.15s
ERROR sbt command failed: SBT_OPTS="-Xss128m" set bloopExportJarClassifiers in Global := Some(Set("sources")) bloopInstall
INFO  running 'SBT_OPTS="-Xss128m" set bloopExportJarClassifiers in Global := Some(Set("sources")) bloopInstall'
Feb 14, 2020 3:41:09 PM com.zaxxer.nuprocess.osx.OsxProcess start
WARNING: Exception thrown from handler
java.lang.RuntimeException: Invocation of posix_spawn() failed, return code: 2, last error: 17
	at com.zaxxer.nuprocess.internal.BasePosixProcess.checkReturnCode(BasePosixProcess.java:639)
	at com.zaxxer.nuprocess.osx.OsxProcess.start(OsxProcess.java:85)
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at scala.meta.internal.metals.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:80)
	at scala.meta.internal.metals.BloopInstall.$anonfun$runUnconditionally$1(BloopInstall.scala:53)
	at scala.meta.internal.builds.BloopPluginBuildTool.bloopInstall(BloopPluginBuildTool.scala:15)
	at scala.meta.internal.metals.BloopInstall.runUnconditionally(BloopInstall.scala:51)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1352)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1338)
	at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

INFO  build tool exit: -2147483648
INFO  time: ran 'sbt bloopInstall' in 51ms
ERROR sbt command failed: SBT_OPTS="-Xss128m" set bloopExportJarClassifiers in Global := Some(Set("sources")) bloopInstall
INFO  running 'SBT_OPTS="-Xss128m" set bloopExportJarClassifiers in Global := Some(Set("sources")) bloopInstall'
Feb 14, 2020 3:41:11 PM com.zaxxer.nuprocess.osx.OsxProcess start
WARNING: Exception thrown from handler
java.lang.RuntimeException: Invocation of posix_spawn() failed, return code: 2, last error: 17
	at com.zaxxer.nuprocess.internal.BasePosixProcess.checkReturnCode(BasePosixProcess.java:639)
	at com.zaxxer.nuprocess.osx.OsxProcess.start(OsxProcess.java:85)
	at com.zaxxer.nuprocess.osx.OsxProcessFactory.createProcess(OsxProcessFactory.java:34)
	at com.zaxxer.nuprocess.NuProcessBuilder.start(NuProcessBuilder.java:266)
	at scala.meta.internal.metals.BloopInstall.runArgumentsUnconditionally(BloopInstall.scala:80)
	at scala.meta.internal.metals.BloopInstall.$anonfun$runUnconditionally$1(BloopInstall.scala:53)
	at scala.meta.internal.builds.BloopPluginBuildTool.bloopInstall(BloopPluginBuildTool.scala:15)
	at scala.meta.internal.metals.BloopInstall.runUnconditionally(BloopInstall.scala:51)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1352)
	at scala.meta.internal.metals.MetalsLanguageServer.slowConnectToBuildServer(MetalsLanguageServer.scala:1338)
	at scala.meta.internal.metals.MetalsLanguageServer.executeCommand(MetalsLanguageServer.scala:1165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

INFO  build tool exit: -2147483648
INFO  time: ran 'sbt bloopInstall' in 11ms
ERROR sbt command failed: SBT_OPTS="-Xss128m" set bloopExportJarClassifiers in Global := Some(Set("sources")) bloopInstall
WARN  no build target for: /Users/test/test/src/main/scala/example/Hello.scala
```
Metal version: 0.8.0
Editor: VSCode 
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

Running 
```sbt bloopInstall``` from the terminal outside VSCode is fine. But importing project failed, even for manual importing from the metals. 

Thanks!

**Comment by tgodzik** [comment]
@ZiluTian No solution currently, we need to remove NuProcess most likely, since that's an issue with that library.

**Comment by olafurpg** [comment]
A workaround is to run `sbt bloopInstall` from the command-line instead of running "import build".

**Comment by tgodzik** [comment]
To enable browsing sources we need to run:
`sbt -Dbloop.export-jar-classifiers=sources bloopInstall`

**Comment by olafurpg** [comment]
I have the following line in my zshrc

```
❯ cat ~/.zshrc | grep BLOOP
export BLOOP_EXPORT_JAR_CLASSIFIERS=sources
```

It's often faster to run `bloopInstall` from an sbt shell instead of "import build" from Metals.

**Comment by olafurpg** [comment]
We should try upgrading like bloop https://github.com/scalacenter/bloop/pull/1178

**Comment by tgodzik** [comment]
we are already on the newest version `1.2.6` thanks to Scala Steward :sweat_smile:
